### ISSUE TITLE
[FEATURE] 기본적인 상호작용 스크립트 생성하기

### ISSUE THREAD

**Issue by gjsk132** [pknu-wap/2024_1_Game1_catTown#20]
### 작업 사항

모든 아이템이 가지는 InteractionBasic을 생성하고, 상호작용 할 수 있도록 한다.

### Todo

- [x] InteractionBasic 스크립트 생성하기
- [x] player와 상호작용하는 오브젝트와 충돌했을 때, 이를 확인할 수 있도록 하기
- [x] 충돌했을 때, 이벤트가 일어날 수 있도록 하기
- [x] 생성할 이벤트 - 사라질지 아닐지 (`isDisappear`) ( 일회성 아이템의 경우 사라짐 )
- [x] 생성할 이벤트 - player가 어떤 효과를 얻게 될지
- [x] item일 때 움직임 구현하기 ( 공중에 띄우기 )
- [x] item일 때 움직임 구현하기 ( 공중에서 조금씩 돌아갈 수 있도록 )

### 기타사항

해당 스크립트는 이후에 만들 모든 아이템이 가지는 공통적인 부분을 작업하려고 합니다.

player가 각각 어떤 효과를 얻게 될지는 해당 스크립트를 상속 받아서 새로운 스크랩트에서 작업하려고 합니다.

**Comment by gjsk132** [comment]
damage 관련 스크립트 작성 완료

충돌 관련 스크립트 추가 필요 -> 완료 ( 사운드 넣으면 끝 )

추가적으로 적용할 무료 에셋 찾아보기 ( 완료  > 더 import할 거 없음 )
