### ISSUE TITLE
[FEATURE] 2번째 맵 기획 및 구현할 기능

### ISSUE THREAD

**Issue by gjsk132** [pknu-wap/2024_1_Game1_catTown#32]
### 전체적인 스토리 기획

[ 2번째 맵 ] > 아파트

어떠한 과정으로 흘러감 

방안에서 퍼즐 어쩌고저쩌고, 풀고 거실엔 자는 사람 어쩌고 저쩌고 할 겁니다.

### Todo

- [ ] 맵 : 서랍장 열리고 닫을 수 있게 / 옷장 열리고 닫을 수 있게 / 에셋 ( 충돌해서 위험지수가 올라갈 것들 ( 물건들  ex. 화분 바닥에 쓰레기)

- [ ] 플레이어 : 숙여서 들어갈 수 있는게 필요합니다. / 상호작용 / 위험 지수

- [ ] 오브젝트 : 자물쇠 / 열쇠 / 상자 / 종이 상호작용 / 물건과 충돌하면 소리 나도록

- [ ] 적 : 움직이지 않고, 위험 지수가 일정 이상 올라가게 된다면, 쫓아와서 숨을 수 없이 잡힘( 일어났을 때, 시야 안에 있다면 쫓아오는걸로 어떤가요 )

### 기타사항

위험 지수를 추가해야 한다.

ai는 한 위치에 고정

소리가 발생할 수 있는 오브젝트를 추가로 할 예정이다.

**Comment by gjsk132** [comment]
플레이어 캡슐을 고양이로 변경해서 카메라 시점 조절 필요
( 숙이기도 같이 높이 조정해야할 것 같습니다. )
