### ISSUE TITLE
[FEATURE] 1번째 맵 기획 및 구현할 기능

### ISSUE THREAD

**Issue by junyoungnnn** [pknu-wap/2024_1_Game1_catTown#33]
### 작업 사항

지하수로는 3층까지 있는데 1층에는 monster가 없는 미로찾기이고 2층에서 monster에게 쫒기며 3층 탈출구까지 이동해야 함.
매 층마다 리스폰 지점이 있고 플레이어는 monster에게 공격당할 시 화면이 붉어진다.

### Todo

- [x] 지하 수로 Bake
- [x] 지하 수로에 플레이어 배치
- [x] 지하 수로에 monster 배치
- [x] 수로 사운드 추가
- [x] monster 사운드 추가
- [x] 플레이어와 몬스터의 스피드 조정
- [x] 플레이어 체력 구현
- [x] 플레이어 체력이 낮아지면 화면을 붉게 만들기 >> 체력바로 변경
- [x] 다음 맵으로 이동
- [x] 마우스커서 추가

### 기타사항
* 타이틀에서 수로까지 가기전 컷씬 추가
_No response_

**Comment by gjsk132** [comment]
1. 체력 회복 및 데미지 오브젝트 구현 완료
2. 구현된 체력 오브젝트 첫번째 맵에 배치 완료
3. 사다리 상호작용 텍스트 띄우기 완료
