### ISSUE TITLE
[CONFLICT] 맥 윈도우 개행 문자로 인한 깃허브 충돌 해결

### ISSUE THREAD

**Issue by gjsk132** [pknu-wap/2024_1_Game1_catTown#9]
### 충돌

맥 윈도우 개행 문자로 인한 깃허브 충돌 발생

맥 -> LF
윈도우 -> CRLF

모든 CRLF를 LF로 변환해서 올릴 수 있도록 수정하기

### Todo

- [x] .gitattributes 추가
- [x] 순차적으로 한 사람씩 유니티 파일 병합하면서 충돌 확인
- [x] 박현 유니티
- [x] 노준영 유니티
- [x] 서하진 유니티
- [x]  서하진 남은 작업 맥에서 pull / push / merge 해보기
- [x] 허찬 pull해서 unity 확인 / 새로운 branch 생성 후 push / commit 생활화
- [x] 허나영 pull해서 unity 확인

### 기타사항

mac에서 모든 하위폴더에 생성되는 DS_Store 파일을 `.gitignore`에 추가함
